deleting env file and ignoring in .gitignore file in the repository c…
generaciondesafiante/Regresemos_a_nuestra_casa_CMS_Resources_and_Coureses pull request #4
Opened 2024-01-03 17:13 UTC by Daniielmayo

deleting env file and ignoring in .gitignore file

2024-01-03 19:39 UTC, DanielCalleCO requested changes
PTAL of my comments buddy. Nice job

2024-01-03 19:39 UTC, DanielCalleCO commented on .gitignore
> +
Dani, I think these lines should be deleted

2024-01-03 19:39 UTC, DanielCalleCO commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/node,expressionengine,windows,linux,macos
This line should be deleted too

2024-01-03 20:12 UTC, DanielCalleCO approved these changes

2024-01-04 13:53 UTC, cristianarce89 approved these changes

2024-01-04 13:53 UTC, cristianarce89 approved these changes

2024-01-04 21:17 UTC, abdulflorez approved these changes

2024-01-09 12:46 UTC, merged